apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-case.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-case.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-case.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_TOPIC
              value: "{{ .Values.env.kafkaTopic }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Release.Name }}-kafka:9092"
            - name: MONGO_URI
              value: "mongodb://devopsuser:devopspass@{{ .Release.Name }}-mongodb:27017/?authSource=admin"
            - name: MONGO_DB
              value: "devops-db"
            - name: MONGO_COLLECTION
              value: "devops-values"
