apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-case.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-case.name" . }}
      app.kubernetes.io/name: {{ include "devops-case.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-case.name" . }}
        app.kubernetes.io/name: {{ include "devops-case.name" . }}
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z devops-case-kafka 9092; do echo waiting for kafka; sleep 5; done' ]

      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "devops-case.fullname" . }}-config
                  key: KAFKA_TOPIC

            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "devops-case.fullname" . }}-config
                  key: KAFKA_SERVER

            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "devops-case.fullname" . }}-config
                  key: MONGO_HOST

            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "devops-case.fullname" . }}-config
                  key: MONGO_PORT

            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "devops-case.fullname" . }}-config
                  key: MONGO_DB_NAME

            - name: MONGO_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "devops-case.fullname" . }}-config
                  key: MONGO_COLLECTION

            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: devops-case-secret
                  key: MONGO_USERNAME

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-case-secret
                  key: MONGO_PASSWORD
